### PR TITLE
 Use nightly pytorch build

### PR DESCRIPTION
**Pull request by Delaunay**

### CODE REVIEW

**Comment by Delaunay** [comment]
Failures

```
Error Report
------------

resnet152.0
^^^^^^^^^^^
    ImportError: cannot import name 'LightningLoggerBase' from 'pytorch_lightning.loggers' (/opt/actions-runner/_work/milabench/milabench/output/venv/lightning/lib/python3.9/site-packages/pytorch_lightning/loggers/__init__.py)

vit_l_32.0
^^^^^^^^^^
    ImportError: cannot import name 'LightningLoggerBase' from 'pytorch_lightning.loggers' (/opt/actions-runner/_work/milabench/milabench/output/venv/lightning/lib/python3.9/site-packages/pytorch_lightning/loggers/__init__.py)

Summary
-------
    Success: 35
    Failures: 2
 ```

**Comment by Delaunay** [comment]
If we dont

```
Error Report
------------

resnet152.0
^^^^^^^^^^^
    ModuleNotFoundError: No module named 'torch._six'

vit_l_32.0
^^^^^^^^^^
    ModuleNotFoundError: No module named 'torch._six'

Summary
-------
    Success: 35
    Failures: 2
```

**Comment by Delaunay** [comment]
```

vit_l_32.0 >! Traceback (most recent call last):
vit_l_32.0 >! 
  File "/opt/actions-runner/_work/milabench/milabench/output/venv/lightning/lib/python3.9/site-packages/voir/forward.py", line 81, in __call__
    yield ov.phases.load_script
vit_l_32.0 >! 
  File "/opt/actions-runner/_work/milabench/milabench/output/venv/lightning/lib/python3.9/site-packages/voir/phase.py", line 183, in _step_one
    next_phase = gen.throw(ph.exception)
vit_l_32.0 >! 
  File "/opt/actions-runner/_work/milabench/milabench/milabench/instruments.py", line 383, in profile_gpu
    yield ov.phases.load_script
vit_l_32.0 >! 
  File "/opt/actions-runner/_work/milabench/milabench/output/venv/lightning/lib/python3.9/site-packages/voir/phase.py", line 183, in _step_one
    next_phase = gen.throw(ph.exception)
vit_l_32.0 >! 
  File "/opt/actions-runner/_work/milabench/milabench/milabench/opt.py", line 2, in instrument_argparse
    yield ov.phases.load_script
vit_l_32.0 >! 
  File "/opt/actions-runner/_work/milabench/milabench/output/venv/lightning/lib/python3.9/site-packages/voir/overseer.py", line 55, in run
    func = find_script(script, field)
vit_l_32.0 >! 
  File "/opt/actions-runner/_work/milabench/milabench/output/venv/lightning/lib/python3.9/site-packages/voir/overseer.py", line 90, in find_script
    exec(code, glb, glb)
vit_l_32.0 >! 
  File "/opt/actions-runner/_work/milabench/milabench/output/code/lightning/main.py", line 16, in <module>
    from model import C, H, Model, W
vit_l_32.0 >! 
  File "/opt/actions-runner/_work/milabench/milabench/output/code/lightning/model.py", line 18, in <module>
    from utils import C, H, W, backbone_choice, get_backbone_network
vit_l_32.0 >! 
  File "/opt/actions-runner/_work/milabench/milabench/output/code/lightning/utils.py", line 10, in <module>
    import pl_bolts.datamodules
vit_l_32.0 >! 
  File "/opt/actions-runner/_work/milabench/milabench/output/venv/lightning/lib/python3.9/site-packages/pl_bolts/__init__.py", line 11, in <module>
    from pl_bolts import (  # noqa: E402
vit_l_32.0 >! 
  File "/opt/actions-runner/_work/milabench/milabench/output/venv/lightning/lib/python3.9/site-packages/pl_bolts/callbacks/__init__.py", line 3, in <module>
    from pl_bolts.callbacks.data_monitor import ModuleDataMonitor, TrainingDataMonitor
vit_l_32.0 >! 
  File "/opt/actions-runner/_work/milabench/milabench/output/venv/lightning/lib/python3.9/site-packages/pl_bolts/callbacks/data_monitor.py", line 6, in <module>
    from pytorch_lightning.loggers import LightningLoggerBase, TensorBoardLogger, WandbLogger
vit_l_32.0 >! 
ImportError: cannot import name 'LightningLoggerBase' from 'pytorch_lightning.loggers' (/opt/actions-runner/_work/milabench/milabench/output/venv/lightning/lib/python3.9/site-packages/pytorch_lightning/loggers/__init__.py)
```

**Comment by Delaunay** [comment]
Even newest lightning package we have the issue

```
Error Report
------------

resnet152.0
^^^^^^^^^^^
    ModuleNotFoundError: No module named 'torch._six'

vit_l_32.0
^^^^^^^^^^
    ModuleNotFoundError: No module named 'torch._six'

Summary
-------
    Success: 35
    Failures: 2
    ```

**Comment by Delaunay** [comment]
```
bench                Plan          metric     1.13  NIGHTLY        %
-------------------------------------------------------------------
hf_t5                         train_rate     2.22     2.21    -0.38
resnet50                      train_rate    36.31    55.22    52.06
efficientnet_b0               train_rate    85.08    86.72     1.92
td3                           train_rate 13971.88 12949.84    -7.31
regnet_y_128gf                train_rate     1.26     1.00   -21.22
dlrm                          train_rate 38091.68 41417.27     8.73
bert                          train_rate    17.85    17.87     0.10
speech_transformer            train_rate    35.87    36.57     1.94
soft_actor_critic             train_rate 12258.97 13545.01    10.49
convnext_large                train_rate     2.10     1.35   -35.76
stargan                       train_rate    24.76    33.38    34.80
learning_to_paint             train_rate   802.15   803.88     0.21
super_slomo                   train_rate     1.29     1.47    14.05
efficientnet_b4               train_rate    27.23    29.47     8.22
ppo                  DDP      train_rate   834.84   852.83     2.16
hf_reformer                   train_rate     3.71     3.71     0.07
squeezenet1_1                 train_rate   163.83   181.22    10.61
efficientnet_b7               train_rate    11.18    10.58    -5.43
resnet152            DDP      train_rate    96.54    99.90     3.48
vit_l_32             DDP      train_rate    51.80    48.60    -6.17
```

**Review by breuleux — APPROVED** [review]

**Pull request merged**
