### PR TITLE
Add Dockerfile concept

### PR DESCRIPTION
**Pull request by Delaunay**

### CODE REVIEW

**Comment by Delaunay** [comment]
To make the container really useful we need to pre-install the benchmarks, and maybe even pre-prepare.
so users can simply run the benchmark right away reducing the risk of issues arising during setup.

The problem is we have multiple configs for different vendors

1. One container per config 
2. One container for everything (lots of duplicates)

Having one config per vendor is problematic as it muddies the water in terms of comparability.
Specially since we only need very few packages to be different (pytorch & all)

**Comment by Delaunay** [comment]
Once published it looks like https://github.com/Delaunay/milabench/pkgs/container/milabench

**Comment by Delaunay** [comment]
```
#16 208.1 Failed to install torchbenchmark requirements:
#16 208.1 b"  error: subprocess-exited-with-error\n  \n  \xc3\x97 Building wheel for tokenizers (pyproject.toml) did not run successfully.\n  \xe2\x94\x82 exit code: 1\n  \xe2\x95\xb0\xe2\x94\x80> [51 lines of output]\n      running bdist_wheel\n      running build\n      running build_py\n      creating build\n      creating build/lib.linux-x86_64-cpython-310\n      creating build/lib.linux-x86_64-cpython-310/tokenizers\n      copying py_src/tokenizers/__init__.py -> build/lib.linux-x86_64-cpython-310/tokenizers\n      creating build/lib.linux-x86_64-cpython-310/tokenizers/models\n      copying py_src/tokenizers/models/__init__.py -> build/lib.linux-x86_64-cpython-310/tokenizers/models\n      creating build/lib.linux-x86_64-cpython-310/tokenizers/decoders\n      copying py_src/tokenizers/decoders/__init__.py -> build/lib.linux-x86_64-cpython-310/tokenizers/decoders\n      creating build/lib.linux-x86_64-cpython-310/tokenizers/normalizers\n      copying py_src/tokenizers/normalizers/__init__.py -> build/lib.linux-x86_64-cpython-310/tokenizers/normalizers\n      creating build/lib.linux-x86_64-cpython-310/tokenizers/pre_tokenizers\n      copying py_src/tokenizers/pre_tokenizers/__init__.py -> build/lib.linux-x86_64-cpython-310/tokenizers/pre_tokenizers\n      creating build/lib.linux-x86_64-cpython-310/tokenizers/processors\n      copying py_src/tokenizers/processors/__init__.py -> build/lib.linux-x86_64-cpython-310/tokenizers/processors\n      creating build/lib.linux-x86_64-cpython-310/tokenizers/trainers\n      copying py_src/tokenizers/trainers/__init__.py -> build/lib.linux-x86_64-cpython-310/tokenizers/trainers\n      creating build/lib.linux-x86_64-cpython-310/tokenizers/implementations\n      copying py_src/tokenizers/implementations/sentencepiece_bpe.py -> build/lib.linux-x86_64-cpython-310/tokenizers/implementations\n      copying py_src/tokenizers/implementations/base_tokenizer.py -> build/lib.linux-x86_64-cpython-310/tokenizers/implementations\n      copying py_src/tokenizers/implementations/bert_wordpiece.py -> build/lib.linux-x86_64-cpython-310/tokenizers/implementations\n      copying py_src/tokenizers/implementations/__init__.py -> build/lib.linux-x86_64-cpython-310/tokenizers/implementations\n      copying py_src/tokenizers/implementations/byte_level_bpe.py -> build/lib.linux-x86_64-cpython-310/tokenizers/implementations\n      copying py_src/tokenizers/implementations/sentencepiece_unigram.py -> build/lib.linux-x86_64-cpython-310/tokenizers/implementations\n      copying py_src/tokenizers/implementations/char_level_bpe.py -> build/lib.linux-x86_64-cpython-310/tokenizers/implementations\n      creating build/lib.linux-x86_64-cpython-310/tokenizers/tools\n      copying py_src/tokenizers/tools/visualizer.py -> build/lib.linux-x86_64-cpython-310/tokenizers/tools\n      copying py_src/tokenizers/tools/__init__.py -> build/lib.linux-x86_64-cpython-310/tokenizers/tools\n      copying py_src/tokenizers/__init__.pyi -> build/lib.linux-x86_64-cpython-310/tokenizers\n      copying py_src/tokenizers/models/__init__.pyi -> build/lib.linux-x86_64-cpython-310/tokenizers/models\n      copying py_src/tokenizers/decoders/__init__.pyi -> build/lib.linux-x86_64-cpython-310/tokenizers/decoders\n      copying py_src/tokenizers/normalizers/__init__.pyi -> build/lib.linux-x86_64-cpython-310/tokenizers/normalizers\n      copying py_src/tokenizers/pre_tokenizers/__init__.pyi -> build/lib.linux-x86_64-cpython-310/tokenizers/pre_tokenizers\n      copying py_src/tokenizers/processors/__init__.pyi -> build/lib.linux-x86_64-cpython-310/tokenizers/processors\n      copying py_src/tokenizers/trainers/__init__.pyi -> build/lib.linux-x86_64-cpython-310/tokenizers/trainers\n      copying py_src/tokenizers/tools/visualizer-styles.css -> build/lib.linux-x86_64-cpython-310/tokenizers/tools\n      running build_ext\n      running build_rust\n      error: can't find Rust compiler\n      \n      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.\n      \n      To update pip, run:\n      \n          pip install --upgrade pip\n      \n      and then retry package installation.\n      \n      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs)/ is the recommended way to download and update the Rust compiler toolchain.\n      [end of output]\n  \n  note: This error originates from a subprocess, and is likely not a problem with pip.\n  ERROR: Failed building wheel for tokenizers\nERROR: Could not build wheels for tokenizers, which is required to install pyproject.toml-based projects\n"
```

**Comment by Delaunay** [comment]
```ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device```

We can generate the Container with provided GA

**Comment by breuleux** [comment]
Yeah... the container's fairly big at 15 GB or something like that. Not all benchmarks share the same venv, though, only those in the same group, so one idea would be to use the same venv for all, hopefully without introducing incompatibilities.

> Having one config per vendor is problematic as it muddies the water in terms of comparability.

Not any more than needing different binaries for different CPU architectures, I feel.

**Comment by Delaunay** [comment]
> Not any more than needing different binaries for different CPU architectures, I feel.

It just means we will have to make sure versions are comparable, the risk is having the pytorch differ and end up with different results because of software

**Comment by Delaunay** [comment]
```
$ docker images
REPOSITORY    TAG           IMAGE ID       CREATED             SIZE
milabench     latest        ddb322ff4744   24 minutes ago      24GB
```

**Comment by Delaunay** [comment]
FYI: 

```
du -h -d 1 /opt/milabench/
486M    /opt/milabench/code
499M    /opt/milabench/data
16G     /opt/milabench/venv
160K    /opt/milabench/runs
17G     /opt/milabench/
```

**Comment by Delaunay** [comment]
This one using the default github runner "work" https://github.com/mila-iqia/milabench/actions/runs/4077072381/jobs/7025628333

**Comment by Delaunay** [comment]
But with our runner we have permission issues
```
Run docker/login-action@v2
Logging into ghcr.io...
Error: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/auth": dial unix /var/run/docker.sock: connect: permission denied
```

**Comment by abergeron** [comment]
Just a quick question, but why are you using the self-hosted runner to build docker images?  Just building the images shouldn't require a GPU to be present so we could do that on the normal runners.

**Pull request merged**
