### PR TITLE
automatic batch resize :sparkle: 

### PR DESCRIPTION
**Pull request by Delaunay**

### CODE REVIEW

**Comment by Delaunay** [comment]
H100 - 80Go

**Comment by breuleux** [comment]
That would only work for the models that take a specific input shape, right? Which would be all the torchvision ones and some of the torchbenchmark ones that are tailored to ImageNet, but probably not the transformers.

**Comment by Delaunay** [comment]
Some bench do not respond correctly to a batch size some others get capped :/

**Comment by Delaunay** [comment]
it looks like it works for BERT

**Comment by Delaunay** [comment]
```
$ milabench run --select resnet50-fp16
resnet50-fp16.D0 {'train_rate': 1533.6431689370127}
resnet50-fp16.D0 {'loss': 3454.33203125}
resnet50-fp16.D0 {'train_rate': 1531.1626484374933}
resnet50-fp16.D0 {'loss': 3454.321533203125}
resnet50-fp16.D0 {'train_rate': 1534.0157980552508}
resnet50-fp16.D0 {'loss': 3454.314453125}
resnet50-fp16.D0 {'train_rate': 1531.498356458543}
resnet50-fp16.D0 {'loss': 3454.307373046875}
resnet50-fp16.D0 {'train_rate': 1532.2061841481632}
resnet50-fp16.D0 {'loss': 3454.299072265625}
resnet50-fp16.D0 {'gpudata': {'0': {'memory': [81088.75, 81920.0], 'load': 0.99, 'temperature': 65}}}
resnet50-fp16.D0 {'train_rate': 1530.9698631203746}
resnet50-fp16.D0 End: 2023-03-17 16:58:21.227849
[DONE] Reports directory: /home/mila/delaunap/results/runs/bumufisa.2023-03-17_16:55:32.950114


$ export MILABENCH_GPU_MEM_LIMIT=12000
$ milabench run --select resnet50-fp16
resnet50-fp16.D0 {'gpudata': {'0': {'memory': [10654.75, 81920.0], 'load': 0.98, 'temperature': 66}}}
resnet50-fp16.D0 {'loss': 3443.430419921875}
resnet50-fp16.D0 End: 2023-03-17 17:04:15.206755
[DONE] Reports directory: /home/mila/delaunap/results/runs/juvulato.2023-03-17_17:01:53.067144
```

**Comment by Delaunay** [comment]
Some weird behavior happening right now on  on a few bench I have not even touched

bench | AUTO Batch | Batch Size | (perf +%) | Memory Usage | Memory (x)
-- | -- | -- | -- | -- | --
bert | 191.54 | 432 | 1.22 | 75630.75 | 11.40
convnext_large | 216.07 | 400 | 0.84 | 80518.75 | 2.83
dlrm | 288079.13 |   | 0.91 | 3850.75 | 1.00
efficientnet_b0 | 210.94 | 1664 | 0.82 | 49816.75 | 5.74
efficientnet_b4 | 234.28 | 680 | 0.89 | 81076.75 | 4.63
efficientnet_b7 | 268.4 | 288 | 1.07 | 80798.75 | 6.91
hf_reformer | 33.54 | 200 | 1.04 | 78492.75 | 17.20
hf_t5 | 22.18 | 24 | 1.03 | 66270.75 | 2.83
learning_to_paint | 6286.53 |   | 1.20 | 3390.75 | 1.00
ppo | 1660.48 |   | 0.99 | 2198.75 | 1.00
regnet_y_128gf | 51.06 | 88 | 1.03 | 76202.75 | 4.11
resnet152 | 7548.9 | ? | 13.58 | 4716.75 | 1.56
resnet50-fp16 | 1530.8 | 952 |   | 81088.75 |  
resnet50-fp32 | 664.86 | 864 | 2.55 | 77172.75 | 8.25
soft_actor_critic | 30147.53 |   | 0.97 | 1444.75 | 1.00
speech_transformer | 221.84 |   | 1.00 | 2828.75 | 1.00
squeezenet1_1 | 235.47 | 4096 | 0.91 | 22810.75 | 4.38
stargan | 651.17 |   | 1.00 | 3598.75 | 1.00
super_slomo | 47.47 | 288 | 1.04 | 11762.75 | 1.48
td3 | 28672.73 |   | 1.00 | 2200.75 | 1.00
vit_l_32 | 2785.82 | ? | 4.85 | 10250.75 | 1.05

**Comment by Delaunay** [comment]
So there is two important options

* `MILABENCH_GPU_MEM_LIMIT` to artificially limit a GPU memory capacity
* `MILABENCH_FIXED_BATCH` to disable the batch size computation

**Comment by Delaunay** [comment]
I am doing a re-run with `MILABENCH_GPU_MEM_LIMIT =40000` to see how performance change

**Comment by Delaunay** [comment]
I will try to see if the batch finding logic works on the CI as well

**Comment by Delaunay** [comment]
Implemented in https://github.com/mila-iqia/milabench/pull/177

**Pull request closed without merging**
